# Generated by Django 5.2.6 on 2025-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="images/no_image.jpg", upload_to="images/%Y/%m/%d"
            ),
        ),
    ]
